version: "3.1"

services:
  mongodb:
    image: mongo
    container_name: h2oapi-mongodb
    restart: always
    network_mode: "host"
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  app:
    image: h2oapi:latest
    container_name: h2oapi-app
    restart: always
    network_mode: "host"
    volumes:
      - app:/app
      - /tmp/h2ogpt:/tmp/h2ogpt # user_path for h2ogpt
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile

volumes:
  app:
  mongodb:
